# name: Target Repository Workflow
# on:
#   push:
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:
#   repository_dispatch: #add this
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Testing repo dispatch
#         run: |-
#           echo "This workflow was triggered from another workflow"

name: Listener for ghidra

on:
  repository_dispatch:
  workflow_dispatch:
    - custom

jobs:
  dump:
    runs-on: ubuntu-24.04
    steps:
      - name: Dump event payload
        run: |
          jq . "$GITHUB_EVENT_PATH"