# name: Target Repository Workflow
# on:
#   push:
#   pull_request:
#     branches:
#       - main
#   workflow_dispatch:
#   repository_dispatch: #add this
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Testing repo dispatch
#         run: |-
#           echo "This workflow was triggered from another workflow"

name: Listener for Repository Trigger

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - closed

  workflow_dispatch:
  repository_dispatch:
    types:
      - custom

jobs:
  dump:
    if: github.event.pull_request.merged == true ||
        github.event_name == 'workflow_dispatch' ||
        github.event_name == 'repository_dispatch' ||
        github.event.action == 'opened' ||
        github.event.action == 'edited' ||
        github.event.action == 'reopened'
        
    runs-on: ubuntu-24.04
    steps:
      - name: Dump event payload
        run: |
          jq . "$GITHUB_EVENT_PATH"